# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20180707_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField()),
                ('profile_pic', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
